import { Sintony } from "next/font/google";
import "./globals.css";

const sintony = Sintony({
  weight: ["700", "400"],
  subsets: ["latin"],
});

import Favicon from "./favicon.ico";

export const metadata = {
  title: "Verdens Skove",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon }],
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={sintony.className}>{children}</body>
    </html>
  );
}
