import { Sintony } from "next/font/google";
import "./globals.css";

const sintony = Sintony({
  weight: ["700", "400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Verdens Skove",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sintony.className}>{children}</body>
    </html>
  );
}
